version: "3.8"

services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    container_name: flask_server
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    container_name: react_client
