version: '3.9'
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/your_database_name

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
